### ISSUE TITLE
Finish documentation

### ISSUE THREAD

**Issue by curds01** [MengeCrowdSim/Menge#123]
This is an epic issue intended to serve as the focal point for all documentation related tasks that haven't been done yet.

As each of these tasks are completed, they'll be checked off (with some documentation as to what makes it "complete"). This issue will also be potentially edited to add more tasks as necessary.

## Tasks
  - [ ] Every element implementation is *properly* documented. To be properly documented this requires:
    - Full and meaningful class documentation.
    - The class documentation should have a properly formatted `xml` example explaining all xml parameters.
    - The implementation should be referenced in the corresponding element mark-down file.
    - Update documentation on [Menge site](http://gamma.cs.unc.edu/Menge/) so that it reflects the complete documentation in master.
    - [ ] AgentGenerators
    - [ ] Elevations
    - [ ] ObstacleSets
    - [ ] ProfileSelectors
    - [ ] SpatialQueries
    - [ ] StateSelectors
    - [ ] Actions
    - [ ] Goals
    - [ ] GoalSelectors
    - [ ] Tasks
    - [ ] Transitions
    - [ ] Velocity components
    - [ ] Velocity modifies
  - [ ] Document unique input files
    - [ ] Navigation mesh
    - [ ] Road map
  - [ ] Document scb file format.
  - [ ] Examples (see issue #106)
    - Each example will have a corresponding readme.md file discussing what features it features
    - A central markdown file will enumerate all examples.
    - Some mutual reference between featured element and example.
    - Videos of examples running (and links to those videos) (See #29)
  - [ ] Concept documentation
    - [ ] Obstacles (see issue #59, #117 )

**Comment by chraibi** [comment]
Good luck with that mate. Is GiHub-Pages something for Menge?

**Comment by Bromeon** [comment]
Something I noticed when generating Doxygen, and you might want to consider when adding more documentation: a lot of the tags are not correctly parsed by Doxygen. I think it has to do with indentation of the `@brief` and `@param` tags in the code.

![grafik](https://user-images.githubusercontent.com/708488/55909391-2b5da180-5bdc-11e9-80e1-a493acec88d2.png)

**Comment by curds01** [comment]
@Bromeon Thanks for calling that out. I'll make a concerted effort to render things at each stage to make sure the end result is desired. Up to this point, it's been produced review-free environment with a kind of fire-and-forget method. And the results of that are clear.
